#pragma config(Sensor, in1,    topRitePot,     sensorPotentiometer)
#pragma config(Sensor, in2,    topLeftPot,     sensorPotentiometer)
#pragma config(Sensor, in3,    lowRitePot,     sensorPotentiometer)
#pragma config(Sensor, in4,    lowLeftPot,     sensorPotentiometer)
#pragma config(Motor,  port2,           drvRiteMotr,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           drvLeftMotr,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           topRiteMotr,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           topLeftMotr,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           lowRiteMotr,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           lowLeftMotr,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
  int buffer = 84;
  int fastSpd = 62;
  int spd = 52;
  int slowSpd = 42;
  int joy_x;            // will hold the X value of the analog stick (choices below)
  int joy_y;            // will hold the Y value of the analog stick (choices below)
  int threshold = 10;   // helps to eliminate 'noise' from a joystick that isn't perfectly at (0,0)
task main()
{
  while(1 == 1)
  {
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    //Upper Lift Control
  if(vexRT[Btn6U] == 1 && vexRT[Btn6D] == 1){

}
    else if(vexRT[Btn6U] == 1 && vexRT[Btn6D] == 0)
    {
      if(SensorValue(topRitePot)>SensorValue(topLeftPot)+buffer){
         motor[topRiteMotr] = fastSpd;
         motor[topLeftMotr] = spd;}
      else if(SensorValue(topLeftPot)>SensorValue(topRitePot)+buffer){
         motor[topLeftMotr] = fastSpd;
         motor[topRiteMotr] = spd;}
      else {
         motor[topRiteMotr] = spd;
         motor[topLeftMotr] = spd;}
    }
    else if(vexRT[Btn6U] == 0 && vexRT[Btn6D] == 1)
    {    motor[topRiteMotr] = -slowSpd;
         motor[topLeftMotr] = -slowSpd;
    }
    else
    {    motor[topRiteMotr] = 0;
         motor[topLeftMotr] = 0;
    }


    //Lower Lift Control

    if(vexRT[Btn5U] == 1)
    {
      if(SensorValue(lowRitePot)>SensorValue(lowLeftPot)+buffer){
         motor[lowRiteMotr] = fastSpd;
         motor[lowLeftMotr] = spd;}
      else if(SensorValue(lowLeftPot)>SensorValue(lowRitePot)+buffer){
         motor[lowLeftMotr] = fastSpd;
         motor[lowRiteMotr] = spd;}
      else {
         motor[lowRiteMotr] = spd;
         motor[lowLeftMotr] = spd;}
    }
    else if(vexRT[Btn5D] == 1)
    {    motor[lowRiteMotr] = -slowSpd;
         motor[lowLeftMotr] = -slowSpd;
    }
    else
    {    motor[lowRiteMotr] = 0;
         motor[lowLeftMotr] = 0;
     }
//+++++++++++++++++++++++++++++++++++++++++++++| DRIVE |+++++++++++++++++++++++++++++++++++++++++++++
    joy_x = vexRT[Ch1];   // This is the RIGHT analog stick.  For LEFT, change 'Ch1' to 'Ch4'.
    joy_y = vexRT[Ch2];   // This is the RIGHT analog stick.  For LEFT, change 'Ch2' to 'Ch3'.

    // Forward, and swing turns: (both abs(X) and abs(Y) are above the threshold, and Y is POSITIVE)
    if((abs(joy_x) > threshold) && (abs(joy_y) > threshold) && (joy_y > 0))
    {
      motor[drvLeftMotr]  = (joy_y + joy_x)/2;
      motor[drvRiteMotr] = (joy_y - joy_x)/2;
    }
    // Backwards and swing turns: (both abs(X) and abs(Y) are above the threshold, and Y is NEGATIVE)
    else if((abs(joy_x) > threshold) && (abs(joy_y) > threshold) && (joy_y < 0))
    {
      motor[drvLeftMotr]  = (joy_y - joy_x)/2;
      motor[drvRiteMotr] = (joy_y + joy_x)/2;
    }
    // Turning in place: (abs(X) is above the threshold, abs(Y) is below the threshold)
    else if((abs(joy_x) > threshold) && (abs(joy_y) < threshold))
    {
      motor[drvLeftMotr]  = joy_x;
      motor[drvRiteMotr] = (-1 * joy_x);
    }
    // Standing still: (both abs(X) and abs(Y) are below the threshold)
    else
    {
      motor[drvLeftMotr]  = 0;
      motor[drvRiteMotr] = 0;
    }
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  }
}
