#pragma config(Sensor, in1,    topRitePot,     sensorPotentiometer)
#pragma config(Sensor, in2,    topLeftPot,     sensorPotentiometer)
#pragma config(Sensor, in3,    lowRitePot,     sensorPotentiometer)
#pragma config(Sensor, in4,    lowLeftPot,     sensorPotentiometer)
#pragma config(Motor,  port2,           topRiteMotr,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           topLeftMotr,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           lowRiteMotr,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           lowLeftMotr,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define ABS(x) (x)>0 ? (x) : (-(x))
int buffer = 84;
int fastSpd = 62;
int spd = 52;
int slowSpd = 42;
task main()
{
  while(1 == 1)
  {

    //Upper Lift Control
  if(vexRT[Btn6U] == 1 && vexRT[Btn6D] == 1){

}
    else if(vexRT[Btn6U] == 1 && vexRT[Btn6D] == 0)
    {
      if(SensorValue(topRitePot)>SensorValue(topLeftPot)+buffer){
         motor[topRiteMotr] = fastSpd;
         motor[topLeftMotr] = spd;}
      else if(SensorValue(topLeftPot)>SensorValue(topRitePot)+buffer){
         motor[topLeftMotr] = fastSpd;
         motor[topRiteMotr] = spd;}
      else {
         motor[topRiteMotr] = spd;
         motor[topLeftMotr] = spd;}
    }
    else if(vexRT[Btn6U] == 0 && vexRT[Btn6D] == 1)
    {    motor[topRiteMotr] = -slowSpd;
         motor[topLeftMotr] = -slowSpd;
    }
    else
    {    motor[topRiteMotr] = 0;
         motor[topLeftMotr] = 0;
    }


    //Lower Lift Control

    if(vexRT[Btn5U] == 1)
    {
      if(SensorValue(lowRitePot)>SensorValue(lowLeftPot)+buffer){
         motor[lowRiteMotr] = fastSpd;
         motor[lowLeftMotr] = spd;}
      else if(SensorValue(lowLeftPot)>SensorValue(lowRitePot)+buffer){
         motor[lowLeftMotr] = fastSpd;
         motor[lowRiteMotr] = spd;}
      else {
         motor[lowRiteMotr] = spd;
         motor[lowLeftMotr] = spd;}
    }
    else if(vexRT[Btn5D] == 1)
    {    motor[lowRiteMotr] = -slowSpd;
         motor[lowLeftMotr] = -slowSpd;
    }
    else
    {    motor[lowRiteMotr] = 0;
         motor[lowLeftMotr] = 0;
     }
  }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
